upgrades:
  valor:
    # Defina aqui o valor unitário inicial do cacto do Upgrade de VALOR.
    inicialcactusvalue: 5000
    # Defina aqui o custo de upgrade inicial do Upgrade de VALOR.
    inicialprice: 2000000000
    # Defina aqui o nível máximo do Upgrade de VALOR.
    maxlevel: 12
  fortune:
    # Defina aqui o valor inicial da fotuna do Upgrade de FORTUNA.
    inicialfortunevalue: 1
    # Defina aqui o custo de upgrade inicial do Upgrade de FORTUNA.
    inicialprice: 100000000
    # Defina aqui o nível máximo do Upgrade de FORTUNA.
    maxlevel: 8
  limit:
    # Defina aqui o tamnho inicial do armazem do Upgrade de LIMITE.
    iniciallimitvalue: 1000
    # Defina aqui o custo de upgrade inicial do Upgrade de LIMITE.
    inicialprice: 100000000000
    # Defina aqui o nível máximo do Upgrade de LIMITE.
    maxlevel: 5
