name: jotage-armazem
version: '${project.version}'
main: com.joaoguedes.jotagearmazem.Jotage_armazem
api-version: '1.8.8'
depend: [PlotSquared, Vault]
commands:
  armazem:
    description: "Abre o armazém do jogador"
    usage: "/armazem"
